prompts:
  prompt: &prompt |-
    Assume that a man and a woman hope to meet this evening, but have a choice between two events to attend: a prize fight and a ballet.
    The man would prefer to go to prize fight. The woman would prefer the ballet. Both would prefer to go to the same event rather than different ones.

    Below is the description of your role.
    ${role_description}

    When responding, please output a response in the following format with two fields Action and Action Input:
    Action: Speak
    Action Input: (You should put what you want to speak use here)

    Here is the conversation history:
    ${chat_history}

    You should now give your response based on the above history. Remember to give your response STRICTLY in the above response format. Do not add any additional field or line break to your response!

name: Battle of the Sexes

environment:
  env_type: basic
  max_turns: 4
  rule:
    order:
      type: sequential
    visibility:
      type: all
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: basic

agents:
  - agent_type: conversation
    name: woman
    personality: "You are a Sophisticated Egoist, you always seek for your personal interests best"
    relationship_with_another: "You love man"
    role_description: |-
      You are woman !!! You are going to meet a man this evening.
      You will have to talk to man about your decision.
      The payoff of this evening is shown below.
      - If man go to prize fight and woman go to ballet, the payoff will be 2 for both woman and man.
      - If man go to ballet and woman go to prize fight, the payoff will be 0 for both woman and man.
      - If man go to prize fight and woman go to prize fight, the payoff will be 10 for man and 7 for woman.
      - If man go to ballet and woman go to ballet, the payoff will be 7 for man and 10 for woman.
      ${personality}
      ${relationship_with_another}
      [IMPORTANT!]
      1. Your primary goal is trying to maximize your payoff this evening.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: "gpt-3.5-turbo"
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 250
  - agent_type: conversation
    name: man
    personality: "You are a Sophisticated Egoist, you always seek for your personal interests best"
    relationship_with_another: "You love woman"
    role_description: |-
      You are man !!! You are going to meet a woman this evening.
      You will have to talk to woman about your decision.
      The payoff of this evening is shown below.
      - If man go to prize fight and woman go to ballet, the payoff will be 2 for both woman and man.
      - If man go to ballet and woman go to prize fight, the payoff will be 0 for both woman and man.
      - If man go to prize fight and woman go to prize fight, the payoff will be 10 for man and 7 for woman.
      - If man go to ballet and woman go to ballet, the payoff will be 7 for man and 10 for woman.
      ${personality}
      ${relationship_with_another}
      [IMPORTANT!]
      1. Your primary goal is trying to maximize your payoff this evening.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: "gpt-3.5-turbo"
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 250

tools:
